project:
  type: book

book:
  title: "Synthetic Population Catalyst"
  chapters:
    - index.qmd
    - part: "Using it"
      chapters:
        - getting_started.qmd
        - installation.qmd
        - using_spc.qmd
        - transform_it.qmd
        - outputs.qmd
        - troubleshooting.qmd
    - part: "Understanding it"
      chapters:
        - understanding.qmd
        - modelling_methods.qmd
        - data_sources.qmd
    - part: "Internals"
      chapters:
        - developer_guide.qmd
        - code_walkthrough.qmd
        - performance.qmd

format:
  html:
    theme: cosmo
  pdf: default
