name: Deploy site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Render site
      run: |
        cd docs
        quarto render --to all --output-dir ./_book_improved_docs

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Build web app
      run: |
        cd web
        npm ci
        npm run build --if-present -- --outDir='dist_improved_docs'
        mv dist_improved_docs ../docs/_book_improved_docs/app

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_book_improved_docs
        destination_dir: improved_docs
