name: Deploy improved-doc branch

on:
  push:
    branches:
      improved-doc

jobs:
  deploy_improved_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: improved-doc

    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Render site
      run: |
        cd docs
        quarto render --to all --output-dir ./_book_improved-doc

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Build web app
      run: |
        cd web
        npm ci
        npm run build --if-present -- --outDir='dist_improved_doc'
        mv dist_improved_doc ../docs/_book_improved-doc/app

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_book-improved_doc
        destination_dir: improved-doc
